"""add telegram_chat_id

Revision ID: f59c0013c4aa
Revises: f6ac13f2c440
Create Date: 2026-06-18 16:33:21.370160+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f59c0013c4aa"
down_revision: str | None = "f6ac13f2c440"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("customers", sa.Column("telegram_chat_id", sa.String(length=64), nullable=True))
    op.create_index(op.f("ix_customers_telegram_chat_id"), "customers", ["telegram_chat_id"], unique=False)
    op.add_column("tenants", sa.Column("telegram_chat_id", sa.String(length=64), nullable=True))
    op.create_index(op.f("ix_tenants_telegram_chat_id"), "tenants", ["telegram_chat_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Rollback migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tenants_telegram_chat_id"), table_name="tenants")
    op.drop_column("tenants", "telegram_chat_id")
    op.drop_index(op.f("ix_customers_telegram_chat_id"), table_name="customers")
    op.drop_column("customers", "telegram_chat_id")
    # ### end Alembic commands ###
