"""phase 9 security and audit

Revision ID: 48c9211b4f31
Revises: f59c0013c4aa
Create Date: 2026-06-18 16:48:37.800437+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48c9211b4f31'
down_revision: str | None = 'f59c0013c4aa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('table_name', sa.String(length=64), nullable=True),
    sa.Column('record_id', sa.String(length=64), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_action_created_at', 'audit_logs', ['action', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_audit_logs_user_id_created_at', 'audit_logs', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.add_column('admin_users', sa.Column('telegram_chat_id', sa.String(length=64), nullable=True))
    op.add_column('admin_users', sa.Column('is_2fa_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Rollback migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'is_2fa_enabled')
    op.drop_column('admin_users', 'telegram_chat_id')
    op.drop_index('ix_audit_logs_user_id_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_created_at', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')

    # ### end Alembic commands ###
