"""Phase 5 Billing and Voucher Models

Revision ID: 9e82e62ae209
Revises: c0cf4fd5f4ac
Create Date: 2026-06-18 13:59:30.924448+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e82e62ae209'
down_revision: Union[str, None] = 'c0cf4fd5f4ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('voucher_batches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('package_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voucher_batches_package_id'), 'voucher_batches', ['package_id'], unique=False)
    op.create_index(op.f('ix_voucher_batches_tenant_id'), 'voucher_batches', ['tenant_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('billing_period', sa.String(length=64), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('unpaid', 'paid', 'cancelled', name='invoice_status_enum'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.Enum('cash', 'transfer', 'gateway', name='payment_method_enum'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('admin_users_email_key'), 'admin_users', type_='unique')
    op.drop_constraint(op.f('admin_users_username_key'), 'admin_users', type_='unique')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.add_column('customers', sa.Column('is_voucher', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('customers', sa.Column('voucher_batch_id', sa.BigInteger(), nullable=True))
    op.add_column('customers', sa.Column('voucher_password', sa.String(length=64), nullable=True))
    op.drop_constraint(op.f('customers_radius_username_key'), 'customers', type_='unique')
    op.drop_index(op.f('ix_customers_radius_username'), table_name='customers')
    op.create_index(op.f('ix_customers_radius_username'), 'customers', ['radius_username'], unique=True)
    op.create_index(op.f('ix_customers_voucher_batch_id'), 'customers', ['voucher_batch_id'], unique=False)
    op.create_foreign_key(None, 'customers', 'voucher_batches', ['voucher_batch_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('nas_ext_nasname_key'), 'nas_ext', type_='unique')
    op.drop_index(op.f('ix_nas_ext_nasname'), table_name='nas_ext')
    op.create_index(op.f('ix_nas_ext_nasname'), 'nas_ext', ['nasname'], unique=True)
    op.drop_index(op.f('ix_nas_vendor_profiles_is_active'), table_name='nas_vendor_profiles')
    op.drop_constraint(op.f('nas_vendor_profiles_vendor_slug_key'), 'nas_vendor_profiles', type_='unique')
    op.drop_index(op.f('ix_nas_vendor_profiles_vendor_slug'), table_name='nas_vendor_profiles')
    op.create_index(op.f('ix_nas_vendor_profiles_vendor_slug'), 'nas_vendor_profiles', ['vendor_slug'], unique=True)
    op.drop_constraint(op.f('packages_group_name_key'), 'packages', type_='unique')
    op.drop_index(op.f('ix_packages_group_name'), table_name='packages')
    op.create_index(op.f('ix_packages_group_name'), 'packages', ['group_name'], unique=True)
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_constraint(op.f('tenants_name_key'), 'tenants', type_='unique')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Rollback migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=False)
    op.create_unique_constraint(op.f('tenants_name_key'), 'tenants', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=False)
    op.drop_index(op.f('ix_packages_group_name'), table_name='packages')
    op.create_index(op.f('ix_packages_group_name'), 'packages', ['group_name'], unique=False)
    op.create_unique_constraint(op.f('packages_group_name_key'), 'packages', ['group_name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_nas_vendor_profiles_vendor_slug'), table_name='nas_vendor_profiles')
    op.create_index(op.f('ix_nas_vendor_profiles_vendor_slug'), 'nas_vendor_profiles', ['vendor_slug'], unique=False)
    op.create_unique_constraint(op.f('nas_vendor_profiles_vendor_slug_key'), 'nas_vendor_profiles', ['vendor_slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_nas_vendor_profiles_is_active'), 'nas_vendor_profiles', ['is_active'], unique=False)
    op.drop_index(op.f('ix_nas_ext_nasname'), table_name='nas_ext')
    op.create_index(op.f('ix_nas_ext_nasname'), 'nas_ext', ['nasname'], unique=False)
    op.create_unique_constraint(op.f('nas_ext_nasname_key'), 'nas_ext', ['nasname'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_voucher_batch_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_radius_username'), table_name='customers')
    op.create_index(op.f('ix_customers_radius_username'), 'customers', ['radius_username'], unique=False)
    op.create_unique_constraint(op.f('customers_radius_username_key'), 'customers', ['radius_username'], postgresql_nulls_not_distinct=False)
    op.drop_column('customers', 'voucher_password')
    op.drop_column('customers', 'voucher_batch_id')
    op.drop_column('customers', 'is_voucher')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=False)
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=False)
    op.create_unique_constraint(op.f('admin_users_username_key'), 'admin_users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('admin_users_email_key'), 'admin_users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_voucher_batches_tenant_id'), table_name='voucher_batches')
    op.drop_index(op.f('ix_voucher_batches_package_id'), table_name='voucher_batches')
    op.drop_table('voucher_batches')

    # ### end Alembic commands ###
